-- ============================================================================
-- Ilaiyaraaja website — seed data (generated by scripts/gen-seed.mjs)
-- Run AFTER schema.sql, in the Supabase SQL editor. Safe to re-run (upserts).
-- ============================================================================

-- slides (5)
insert into public.slides (id, position, data) values
  ('s1', 0, '{"id":"s1","tag":"Upcoming Concert","title":"Live In Concert World Tour","subtitle":"A live symphonic journey through five decades of unforgettable melody.","image":"https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1800&h=1000&q=80","fallback":"/img/slide-concert.svg","ctaLabel":"View concerts","ctaHref":"/concerts"}'::jsonb),
  ('s2', 1, '{"id":"s2","tag":"Latest Album","title":"New Symphonic Works","subtitle":"Orchestral compositions blending Carnatic tradition with Western classical form.","image":"https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?auto=format&fit=crop&w=1800&h=1000&q=80","fallback":"/img/slide-album.svg","ctaLabel":"Explore compositions","ctaHref":"/compositions?tab=Albums"}'::jsonb),
  ('s3', 2, '{"id":"s3","tag":"On Screen","title":"The Latest Scores","subtitle":"From intimate dramas to sweeping epics, the sound of Indian cinema.","image":"https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=1800&h=1000&q=80","fallback":"/img/slide-movie.svg","ctaLabel":"Browse films","ctaHref":"/compositions?tab=Movies"}'::jsonb),
  ('s4', 3, '{"id":"s4","tag":"Honours","title":"A Legacy of Recognition","subtitle":"Padma Vibhushan, National Awards and a lifetime of global acclaim.","image":"https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1800&h=1000&q=80","fallback":"/img/slide-awards.svg","ctaLabel":"See awards","ctaHref":"/awards"}'::jsonb),
  ('s5', 4, '{"id":"s5","tag":"Life Journey","title":"From Pannaipuram to the World","subtitle":"The story of a self-made maestro who redefined Indian music.","image":"https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=1800&h=1000&q=80","fallback":"/img/slide-journey.svg","ctaLabel":"Read biography","ctaHref":"/biography"}'::jsonb)
on conflict (id) do update set position = excluded.position, data = excluded.data, updated_at = now();

-- news (3)
insert into public.news (id, position, data) values
  ('n1', 0, '{"id":"n1","date":"2026-06-18","kicker":"Symphony","title":"Ilaiyaraaja premieres new symphony with a European orchestra","excerpt":"The maestro conducts a full symphonic work, the latest chapter in a lifelong dialogue between Indian melody and Western classical form.","image":"https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1000&h=700&q=80","fallback":"/img/news-1.svg","source":"Press Release"}'::jsonb),
  ('n2', 1, '{"id":"n2","date":"2026-05-02","kicker":"World Tour","title":"World tour adds new cities across three continents","excerpt":"Fresh dates have been announced for the acclaimed live concert series, bringing the orchestral experience to audiences worldwide.","image":"https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&h=700&q=80","fallback":"/img/news-2.svg","source":"Tour Desk"}'::jsonb),
  ('n3', 2, '{"id":"n3","date":"2026-03-14","kicker":"New Release","title":"A remastered anthology celebrates five decades of melody","excerpt":"Landmark compositions return in pristine sound, curated into a definitive anthology for a new generation of listeners.","image":"https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?auto=format&fit=crop&w=1000&h=700&q=80","fallback":"/img/news-3.svg","source":"Label"}'::jsonb)
on conflict (id) do update set position = excluded.position, data = excluded.data, updated_at = now();

-- posts (4)
insert into public.posts (id, position, data) values
  ('p1', 0, '{"id":"p1","category":"Coming Soon","title":"Releasing Soon","blurb":"A new score, mixed and mastered, is on its way to the screen.","image":"https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&w=900&h=700&q=80","fallback":"/img/post-comingsoon.svg"}'::jsonb),
  ('p2', 1, '{"id":"p2","category":"World Tour","title":"On Tour Worldwide","blurb":"The Maestro takes the stage, a world tour of live orchestral concerts.","image":"https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=900&h=700&q=80","fallback":"/img/post-maestroverse.svg"}'::jsonb),
  ('p3', 2, '{"id":"p3","category":"Live Concert","title":"Live In Concert","blurb":"Timeless melodies performed live with a full symphony orchestra.","image":"https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=900&h=700&q=80","fallback":"/img/post-liveconcert.svg"}'::jsonb),
  ('p4', 3, '{"id":"p4","category":"Studio Sessions","title":"Live From Studio","blurb":"Behind the console, a rare look inside the maestro’s recording sessions.","image":"https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=900&h=700&q=80","fallback":"/img/post-studio.svg"}'::jsonb)
on conflict (id) do update set position = excluded.position, data = excluded.data, updated_at = now();

-- concerts (6)
insert into public.concerts (id, position, data) values
  ('k1', 0, '{"id":"k1","title":"Live In Concert, London","series":"Live In Concert","status":"Upcoming","date":"2026-09-14","venue":"The O2 Arena","city":"London","country":"United Kingdom","bookingUrl":"#","image":"https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=900&h=600&q=80","fallback":"/img/concert-london.svg"}'::jsonb),
  ('k2', 1, '{"id":"k2","title":"Live In Concert, Singapore","series":"Live In Concert","status":"Upcoming","date":"2026-10-05","venue":"Singapore Indoor Stadium","city":"Singapore","country":"Singapore","bookingUrl":"#","image":"https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=900&h=600&q=80","fallback":"/img/concert-singapore.svg"}'::jsonb),
  ('k3', 2, '{"id":"k3","title":"Live In Concert, Toronto","series":"Live In Concert","status":"Upcoming","date":"2026-11-08","venue":"Scotiabank Arena","city":"Toronto","country":"Canada","bookingUrl":"#","image":"https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=900&h=600&q=80","fallback":"/img/concert-toronto.svg"}'::jsonb),
  ('l1', 3, '{"id":"l1","title":"Live In Concert, Chennai","series":"Live In Concert","status":"Completed","date":"2025-12-20","venue":"Nehru Indoor Stadium","city":"Chennai","country":"India","bookingUrl":"#","image":"https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=900&h=600&q=80","fallback":"/img/concert-chennai.svg"}'::jsonb),
  ('l2', 4, '{"id":"l2","title":"Live In Concert, Dubai","series":"Live In Concert","status":"Completed","date":"2025-11-01","venue":"Coca-Cola Arena","city":"Dubai","country":"United Arab Emirates","bookingUrl":"#","image":"https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=900&h=600&q=80","fallback":"/img/concert-dubai.svg"}'::jsonb),
  ('l3', 5, '{"id":"l3","title":"Live In Concert, Sydney","series":"Live In Concert","status":"Completed","date":"2025-09-27","venue":"Qudos Bank Arena","city":"Sydney","country":"Australia","bookingUrl":"#","image":"https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=900&h=600&q=80","fallback":"/img/concert-sydney.svg"}'::jsonb)
on conflict (id) do update set position = excluded.position, data = excluded.data, updated_at = now();

-- compositions (18)
insert into public.compositions (id, position, data) values
  ('c1', 0, '{"id":"c1","title":"Mullum Malarum","year":1978,"language":"Tamil","director":"J. Mahendran","label":"EMI","genre":"Drama","songs":5,"category":"Movies","poster":"/img/poster-mullum-malarum.svg","featured":true}'::jsonb),
  ('c2', 1, '{"id":"c2","title":"Mouna Ragam","year":1986,"language":"Tamil","director":"Mani Ratnam","label":"Echo","genre":"Romance","songs":6,"category":"Movies","poster":"/img/poster-mouna-ragam.svg","featured":true}'::jsonb),
  ('c3', 2, '{"id":"c3","title":"Nayakan","year":1987,"language":"Tamil","director":"Mani Ratnam","label":"Echo","genre":"Crime Drama","songs":5,"category":"Movies","poster":"/img/poster-nayakan.svg","featured":true}'::jsonb),
  ('c4', 3, '{"id":"c4","title":"Sagara Sangamam","year":1983,"language":"Telugu","director":"K. Vishwanath","label":"Saregama","genre":"Musical Drama","songs":7,"category":"Movies","poster":"/img/poster-sagara-sangamam.svg","featured":true}'::jsonb),
  ('c5', 4, '{"id":"c5","title":"Sindhu Bhairavi","year":1985,"language":"Tamil","director":"K. Balachander","label":"HMV","genre":"Musical Drama","songs":8,"category":"Movies","poster":"/img/poster-sindhu-bhairavi.svg"}'::jsonb),
  ('c6', 5, '{"id":"c6","title":"Thalapathi","year":1991,"language":"Tamil","director":"Mani Ratnam","label":"Pyramid","genre":"Drama","songs":6,"category":"Movies","poster":"/img/poster-thalapathi.svg","featured":true}'::jsonb),
  ('c7', 6, '{"id":"c7","title":"Geethanjali","year":1989,"language":"Telugu","director":"Mani Ratnam","label":"Saregama","genre":"Romance","songs":6,"category":"Movies","poster":"/img/poster-geethanjali.svg"}'::jsonb),
  ('c8', 7, '{"id":"c8","title":"Punnagai Mannan","year":1986,"language":"Tamil","director":"K. Balachander","label":"Echo","genre":"Romance","songs":7,"category":"Movies","poster":"/img/poster-punnagai-mannan.svg"}'::jsonb),
  ('c9', 8, '{"id":"c9","title":"Mahanadhi","year":1994,"language":"Tamil","director":"Santhana Bharathi","label":"Pyramid","genre":"Drama","songs":4,"category":"Movies","poster":"/img/poster-mahanadhi.svg"}'::jsonb),
  ('c10', 9, '{"id":"c10","title":"Hey Ram","year":2000,"language":"Tamil / Hindi","director":"Kamal Haasan","label":"Sony Music","genre":"Historical","songs":6,"category":"Movies","poster":"/img/poster-hey-ram.svg"}'::jsonb),
  ('c11', 10, '{"id":"c11","title":"Guru","year":1997,"language":"Malayalam","director":"Rajiv Anchal","label":"Tharangini","genre":"Fantasy Drama","songs":5,"category":"Movies","poster":"/img/poster-guru.svg"}'::jsonb),
  ('c12', 11, '{"id":"c12","title":"Pithamagan","year":2003,"language":"Tamil","director":"Bala","label":"Star Music","genre":"Drama","songs":6,"category":"Movies","poster":"/img/poster-pithamagan.svg"}'::jsonb),
  ('a1', 12, '{"id":"a1","title":"How To Name It?","year":1986,"language":"Instrumental","director":"Ilaiyaraaja","label":"Oriental Records","genre":"Fusion","songs":12,"category":"Albums","poster":"/img/poster-how-to-name-it.svg","featured":true}'::jsonb),
  ('a2', 13, '{"id":"a2","title":"Nothing But Wind","year":1988,"language":"Instrumental","director":"Ilaiyaraaja","label":"HMV","genre":"Fusion","songs":6,"category":"Albums","poster":"/img/poster-nothing-but-wind.svg","featured":true}'::jsonb),
  ('d1', 14, '{"id":"d1","title":"Thiruvasagam In Symphony","year":2005,"language":"Tamil","director":"Ilaiyaraaja","label":"Sruthilaya","genre":"Devotional / Symphony","songs":10,"category":"Devotional","poster":"/img/poster-thiruvasagam.svg","featured":true}'::jsonb),
  ('bs1', 15, '{"id":"bs1","title":"Nayakan, Background Score","year":1987,"language":"Instrumental","director":"Mani Ratnam","label":"Echo","genre":"Score","songs":0,"category":"Background Score","poster":"/img/poster-nayakan.svg"}'::jsonb),
  ('bs2', 16, '{"id":"bs2","title":"Thalapathi, Background Score","year":1991,"language":"Instrumental","director":"Mani Ratnam","label":"Pyramid","genre":"Score","songs":0,"category":"Background Score","poster":"/img/poster-thalapathi.svg"}'::jsonb),
  ('im1', 17, '{"id":"im1","title":"Symphonic Works","year":1993,"language":"Instrumental","director":"Ilaiyaraaja","label":"Royal Philharmonic","genre":"Symphony","songs":8,"category":"Independent Music","poster":"/img/poster-nothing-but-wind.svg"}'::jsonb)
on conflict (id) do update set position = excluded.position, data = excluded.data, updated_at = now();

-- products (9)
insert into public.products (id, position, data) values
  ('sp1', 0, '{"id":"sp1","name":"Ilaiyaraaja, The Maestro (Hardcover)","type":"Books","price":1499,"currency":"₹","image":"/img/shop-book-1.svg","badge":"Bestseller"}'::jsonb),
  ('sp2', 1, '{"id":"sp2","name":"A Life in Music, Illustrated Biography","type":"Books","price":1899,"currency":"₹","image":"/img/shop-book-2.svg"}'::jsonb),
  ('sp3', 2, '{"id":"sp3","name":"Golden Melodies, Compact Disc","type":"CD","price":599,"currency":"₹","image":"/img/shop-cd-1.svg"}'::jsonb),
  ('sp4', 3, '{"id":"sp4","name":"Symphonic Works, Compact Disc","type":"CD","price":649,"currency":"₹","image":"/img/shop-cd-2.svg","badge":"New"}'::jsonb),
  ('sp5', 4, '{"id":"sp5","name":"Timeless Classics, Vinyl LP","type":"Vinyl","price":2499,"currency":"₹","image":"/img/shop-vinyl-1.svg","badge":"Limited"}'::jsonb),
  ('sp6', 5, '{"id":"sp6","name":"The Fusion Years, Vinyl LP","type":"Vinyl","price":2699,"currency":"₹","image":"/img/shop-vinyl-2.svg"}'::jsonb),
  ('sp7', 6, '{"id":"sp7","name":"Isaignani Signature Tee","type":"Merchandise","price":899,"currency":"₹","image":"/img/shop-merch-1.svg"}'::jsonb),
  ('sp8', 7, '{"id":"sp8","name":"Treble Clef Art Print","type":"Merchandise","price":749,"currency":"₹","image":"/img/shop-merch-2.svg"}'::jsonb),
  ('sp9', 8, '{"id":"sp9","name":"The Complete Collection, Box Set","type":"Music Collection","price":4999,"currency":"₹","image":"/img/shop-collection.svg","badge":"Collector’s Edition"}'::jsonb)
on conflict (id) do update set position = excluded.position, data = excluded.data, updated_at = now();

-- gallery (11)
insert into public.gallery (id, position, data) values
  ('p1', 0, '{"id":"p1","title":"Isaignani","caption":"The maestro, in portrait","image":"/img/ilaiyaraaja-portrait-color.jpg","fallback":"/img/hero-portrait.svg","span":"tall"}'::jsonb),
  ('p2', 1, '{"id":"p2","title":"The Composer","caption":"A moment of music","image":"/img/ilaiyaraaja-portrait-bw.jpg","fallback":"/img/bio-portrait.svg","span":"normal"}'::jsonb),
  ('g1', 2, '{"id":"g1","title":"At the Podium","caption":"Conducting a live orchestra","image":"https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&h=800&q=80","fallback":"/img/gallery-1.svg","span":"normal"}'::jsonb),
  ('g2', 3, '{"id":"g2","title":"In the Studio","caption":"Behind the mixing console","image":"https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&w=800&h=800&q=80","fallback":"/img/gallery-2.svg","span":"normal"}'::jsonb),
  ('g3', 4, '{"id":"g3","title":"The Manuscript","caption":"Where a melody begins","image":"https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&h=1000&q=80","fallback":"/img/gallery-3.svg","span":"tall"}'::jsonb),
  ('g4', 5, '{"id":"g4","title":"Rehearsal","caption":"With the ensemble","image":"https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&h=800&q=80","fallback":"/img/gallery-4.svg","span":"normal"}'::jsonb),
  ('g5', 6, '{"id":"g5","title":"Live In Concert","caption":"On stage","image":"https://images.unsplash.com/photo-1487215078519-e21cc028cb29?auto=format&fit=crop&w=800&h=800&q=80","fallback":"/img/gallery-5.svg","span":"normal"}'::jsonb),
  ('g6', 7, '{"id":"g6","title":"The Grand Hall","caption":"A cathedral of sound","image":"https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=800&h=1000&q=80","fallback":"/img/gallery-6.svg","span":"tall"}'::jsonb),
  ('g7', 8, '{"id":"g7","title":"Recording Session","caption":"Layering the orchestra","image":"https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&h=800&q=80","fallback":"/img/gallery-7.svg","span":"normal"}'::jsonb),
  ('g8', 9, '{"id":"g8","title":"Applause","caption":"A standing ovation","image":"https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=800&h=800&q=80","fallback":"/img/gallery-8.svg","span":"normal"}'::jsonb),
  ('g9', 10, '{"id":"g9","title":"Legacy","caption":"Five decades of music","image":"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=800&h=1000&q=80","fallback":"/img/gallery-9.svg","span":"tall"}'::jsonb)
on conflict (id) do update set position = excluded.position, data = excluded.data, updated_at = now();

-- quiz (6)
insert into public.quiz (id, position, data) values
  ('q1', 0, '{"id":"q1","question":"In which year was Ilaiyaraaja born?","options":["1938","1943","1950","1955"],"answer":1,"fact":"Ilaiyaraaja was born on 2 June 1943 in Pannaipuram, Tamil Nadu."}'::jsonb),
  ('q2', 1, '{"id":"q2","question":"What is the honorific title given to Ilaiyaraaja?","options":["Isaignani","Kalaimamani","Nadhaswaram","Sangeetha Kalanidhi"],"answer":0,"fact":"“Isaignani” means “the wise man of music”."}'::jsonb),
  ('q3', 2, '{"id":"q3","question":"Ilaiyaraaja was the first Asian to compose a full symphony recorded by which orchestra?","options":["Berlin Philharmonic","Vienna Philharmonic","Royal Philharmonic Orchestra","London Symphony Orchestra"],"answer":2,"fact":"He recorded a full symphony with the Royal Philharmonic Orchestra in London."}'::jsonb),
  ('q4', 3, '{"id":"q4","question":"Which civilian honour did he receive in 2018?","options":["Padma Shri","Padma Bhushan","Padma Vibhushan","Bharat Ratna"],"answer":2,"fact":"He was awarded the Padma Vibhushan in 2018, India’s second-highest civilian honour."}'::jsonb),
  ('q5', 4, '{"id":"q5","question":"Approximately how many films has he scored?","options":["200+","500+","750+","1000+"],"answer":3,"fact":"He has composed music for more than a thousand films across many languages."}'::jsonb),
  ('q6', 5, '{"id":"q6","question":"Which 1986 fusion album blended Bach with Indian classical music?","options":["Nothing But Wind","How To Name It?","Thiruvasagam","Guru"],"answer":1,"fact":"“How To Name It?” (1986) is a landmark fusion album dedicated to Bach and Thyagaraja."}'::jsonb)
on conflict (id) do update set position = excluded.position, data = excluded.data, updated_at = now();

-- awards (16)
insert into public.awards (id, position, data) values
  ('aw1', 0, '{"id":"aw1","year":2018,"title":"Padma Vibhushan","detail":"India’s second-highest civilian award.","category":"Padma"}'::jsonb),
  ('aw2', 1, '{"id":"aw2","year":2010,"title":"Padma Bhushan","detail":"India’s third-highest civilian award.","category":"Padma"}'::jsonb),
  ('aw3', 2, '{"id":"aw3","year":2012,"title":"Sangeet Natak Akademi Award","detail":"For creative music, from India’s national academy.","category":"National"}'::jsonb),
  ('aw4', 3, '{"id":"aw4","year":2013,"title":"National Film Award, Best Music Direction","detail":"For an acclaimed feature-film score.","category":"National"}'::jsonb),
  ('aw5', 4, '{"id":"aw5","year":2010,"title":"National Film Award, Best Music Direction","detail":"For outstanding composition in feature film.","category":"National"}'::jsonb),
  ('aw6', 5, '{"id":"aw6","year":1988,"title":"National Film Award, Best Music Direction","detail":"Recognising a landmark film score.","category":"National"}'::jsonb),
  ('aw7', 6, '{"id":"aw7","year":1985,"title":"National Film Award, Best Music Direction","detail":"Early national recognition for film music.","category":"National"}'::jsonb),
  ('aw8', 7, '{"id":"aw8","year":1979,"title":"Tamil Nadu State Film Award","detail":"Best Music Director, State honours.","category":"State"}'::jsonb),
  ('aw9', 8, '{"id":"aw9","year":1983,"title":"Tamil Nadu State Film Award","detail":"Best Music Director, State honours.","category":"State"}'::jsonb),
  ('aw10', 9, '{"id":"aw10","year":1986,"title":"Filmfare Award South, Best Music Director","detail":"For excellence in South Indian cinema.","category":"Filmfare"}'::jsonb),
  ('aw11', 10, '{"id":"aw11","year":1991,"title":"Filmfare Award South, Best Music Director","detail":"For excellence in South Indian cinema.","category":"Filmfare"}'::jsonb),
  ('aw12', 11, '{"id":"aw12","year":1994,"title":"Filmfare Award South, Best Music Director","detail":"For excellence in South Indian cinema.","category":"Filmfare"}'::jsonb),
  ('aw13', 12, '{"id":"aw13","year":1993,"title":"Royal Philharmonic Orchestra Symphony","detail":"First Asian to compose a full symphony recorded by the RPO, London.","category":"International"}'::jsonb),
  ('aw14', 13, '{"id":"aw14","year":2015,"title":"Honorary Doctorate","detail":"Conferred by a leading university for contribution to music.","category":"Honorary Doctorate"}'::jsonb),
  ('aw15', 14, '{"id":"aw15","year":2018,"title":"Honorary Doctorate","detail":"Recognising a lifetime of musical achievement.","category":"Honorary Doctorate"}'::jsonb),
  ('aw16', 15, '{"id":"aw16","year":2019,"title":"International Recognition","detail":"Celebrated at global music forums and festivals.","category":"International"}'::jsonb)
on conflict (id) do update set position = excluded.position, data = excluded.data, updated_at = now();

