/**
 * Generates supabase/seed.sql from the app's current content.
 *
 * Prereq: `npm run build` with app/seedexport/route.ts present, which emits
 * out/seedexport (JSON). This script reads that file and writes idempotent
 * upserts for every collection. Run: node scripts/gen-seed.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const raw = readFileSync(join(root, 'out', 'seedexport'), 'utf8');
const collections = JSON.parse(raw);

const jsonb = (obj) => `'${JSON.stringify(obj).replace(/'/g, "''")}'::jsonb`;
const text = (s) => `'${String(s).replace(/'/g, "''")}'`;

let out = `-- ============================================================================
-- Ilaiyaraaja website — seed data (generated by scripts/gen-seed.mjs)
-- Run AFTER schema.sql, in the Supabase SQL editor. Safe to re-run (upserts).
-- ============================================================================

`;

for (const [table, items] of Object.entries(collections)) {
  if (!Array.isArray(items) || items.length === 0) continue;
  out += `-- ${table} (${items.length})\n`;
  out += `insert into public.${table} (id, position, data) values\n`;
  out += items
    .map((item, i) => `  (${text(item.id)}, ${i}, ${jsonb(item)})`)
    .join(',\n');
  out += `\non conflict (id) do update set position = excluded.position, data = excluded.data, updated_at = now();\n\n`;
}

writeFileSync(join(root, 'supabase', 'seed.sql'), out);
console.log('✔ Wrote supabase/seed.sql');
